name: PySNC Test

on: [push, pull_request]

jobs:
  install-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    env:
      PYSNC_SERVER: ${{ secrets.PYSNC_SERVER }}
      PYSNC_USERNAME: ${{ secrets.PYSNC_USERNAME }}
      PYSNC_PASSWORD: ${{ secrets.PYSNC_PASSWORD }}
      PYSNC_JWT_CLIENT_SECRET: ${{ secrets.PYSNC_JWT_CLIENT_SECRET }}
      PYSNC_JWT_SHARED_KEY: ${{ secrets.PYSNC_JWT_SHARED_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: run tests
      run: |
        python setup.py test